# VLM model [required]
OPENAI_API_KEY: "sk-X9jXfVLVKHEK6y06p6MRJuEHwvqQX240PPrebQikc1fBXeIS"
OPENAI_BASE_URL: "https://yunwu.ai/v1"
OPENAI_MODEL_NAME: "gpt-5.1"
PROVIDER: "openai"

# Image Gen model [required]
IMAGE_API_KEY: "sk-jYwexkVU6AeQ6oBYFupdDsXFD9yBHptJu61vPbX4sRLA8JEl"
IMAGE_BASE_URL: "https://yunwu.ai/v1"
IMAGE_GEN_MODEL_NAME: "qwen-image-plus"
# IMAGE_EDIT_MODEL_NAME: "qwen-image-edit-plus-2025-12-15"
IMAGE_EDIT_MODEL_NAME: "qwen-image-edit-2509"

# Google API [required]
GOOGLE_API_KEY: "AIzaSyDs18HN7Zv0fiGPRs85uKCglWEy1hknHVI"
GOOGLE_SEARCH_ENGINE_ID: "b59238bad54ef46a0"

# SERPER API [required]
SERPER_API_KEY: "bdf9b167a18e2e9071e4eed39f257aa28d8ad10c"

proxy_on: True
HTTP_PROXY: "http://127.0.0.1:7890"
HTTPS_PROXY: "http://127.0.0.1:7890"

temp_dir:
  default: "./temp"
  image_gen: "./temp/image_gen"
  image_rag: "./temp/image_rag"
  text_rag: "./temp/text_rag"
