# VLM model
OPENAI_API_KEY: "sk-X9jXfVLVKHEK6y06p6MRJuEHwvqQX240PPrebQikc1fBXeIS"
OPENAI_BASE_URL: "https://yunwu.ai/v1"
OPENAI_MODEL_NAME: "gpt-5.1"
PROVIDER: "openai"

# Image Gen model
IMAGE_API_KEY: "sk-X9jXfVLVKHEK6y06p6MRJuEHwvqQX240PPrebQikc1fBXeIS"
IMAGE_BASE_URL: "https://yunwu.ai/v1"
IMAGE_GEN_MODEL_NAME: "qwen-image-plus"
IMAGE_EDIT_MODEL_NAME: "qwen-image-edit-plus-2025-12-15"

# FLUX API
FLUX_API_KEY: "your_flux_api_key"
FLUX_API_URL_SUBMIT: "https://api.us1.bfl.ai/v1/flux-kontext-pro"
FLUX_API_URL_RESULT: "https://api.us1.bfl.ai/v1/get_result"

# Google API
GOOGLE_API_KEY: "AIzaSyDs18HN7Zv0fiGPRs85uKCglWEy1hknHVI"
GOOGLE_SEARCH_ENGINE_ID: "b59238bad54ef46a0"

# SERPER API
SERPER_API_KEY: "bdf9b167a18e2e9071e4eed39f257aa28d8ad10c"
